const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{bk: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{plane: 0},
	{health: 0},
	{Bullet: 0},
	{one: 0},
	{two: 0},
	{three: 0},
	{DestroyOutsideLayout: 0},
	{bullet: 0},
	{Fade: 0},
	{boom: 0},
	{score: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{Sprite: 0},
	{Button: 0}
];

self.InstanceType = {
	bk: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	plane: class extends self.ISpriteInstance {},
	one: class extends self.ISpriteInstance {},
	two: class extends self.ISpriteInstance {},
	three: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	boom: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {}
}